### PR TITLE
[ MAIN ] - fix imports

### PR DESCRIPTION
**Pull request by hamzahsn**
this is a small PR in order to fix the import in Sidebar

### CODE REVIEW

**Comment by hamzahsn** [comment]
> why do we have changes in unrelated snapshots?

which snapshots ?

**Comment by a7madgamal** [comment]
@Weetbix does the snapshot changes make sense to you?

**Comment by a7madgamal** [comment]
the issue is this: when we import anything through index our webpack needs to handle things like fonts etc and also I think we import so much unused code

**Comment by a7madgamal** [comment]
sorry closed by mistake :D

**Comment by Weetbix** [comment]
So can we write a test or a failing case for this? Why didn't storybook fail if the dist is broken for typescript?

**Comment by a7madgamal** [comment]
I can look into an eslint rule, or we can fix imports in web-portal but I think both are technical tasks

**Comment by hamzahsn** [comment]
as @a7madgamal  said that I think it's a trechnical task, and I think it can be fixed in the config for jest and/or storybook but it needs to take a look into that in a seperate investigation

**Comment by a7madgamal** [comment]
@Weetbix the dist is fine, the other portal project needs to fix something in webpack I think

**Pull request merged**
