### PR TITLE
MAIN - restructures some parts of the project

### PR DESCRIPTION
**Pull request by paschalidi**
* restructures file structure
* imports all Components from `src/index.js` this way we are bounded to export a component.
*  adds `.storybook/Container.jsx`, this way the background of the `Component` that is being previewed is slightly more grey. This will help us visualise the space that a `Component` would take.
* The story of each component lives inside the directory of the component, but is not included on the build process. Look [here](https://github.com/UvitaTeam/vivy-components/compare/cp/refactor?expand=1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23) please.
* removes packages that were installed but not used.
* renames several components.

### CODE REVIEW

**Comment by herman-rogers** [comment]
image
image

**Comment by herman-rogers** [comment]
image

**Comment by herman-rogers** [comment]
There's also a strange background color instead of the plain white background that's jarring with the layout.

**Comment by paschalidi** [comment]
> https://user-images.githubusercontent.com/3153479/47007516-b0d62c80-d138-11e8-931c-09040e6b649f.png

I dont get what is that, can u explain?

**Comment by paschalidi** [comment]
> image

can you specify browser. I just tried FF private mode and Chrome Private mode and I didnt see it.

**Comment by herman-rogers** [comment]
There's a package that needs to be updated for security fixes. Just run npm audit fix, should sort it out for you.

**Comment by herman-rogers** [comment]
For the browser I'm using chrome

**Pull request closed without merging**
