### PR TITLE
adds-notes-markdown-file: adds note.md

### PR DESCRIPTION
**Pull request by paschalidi**

### CODE REVIEW

**Review by lanwen — APPROVED** [review]

**Review by lanwen — CHANGES_REQUESTED** [review]
wait, thats public repo, don't expose such data

**Comment by herman-rogers** [comment]
Good point. Let’s discuss how backend handles internal tickets in slack? As we can adopt the same thing.

**Comment by lanwen** [comment]
https://keep.google.com

**Comment by herman-rogers** [comment]
Before we close next time, let's make sure to scrub the data first. Do you know how to get rid of the commit with the file?

**Comment by lanwen** [comment]
no, PRs are immutable :)

**Comment by lanwen** [comment]
No worries, nothing actually secret was leaked, so just remove the branch

**Pull request closed without merging**
