### PR TITLE
Add.icons.and.buttons

### PR DESCRIPTION
**Pull request by herman-rogers**

### CODE REVIEW

**Comment by lanwen** [comment]
are we sure we want to put our icons under MIT license?

**Comment by herman-rogers** [comment]
I don't think it's a big deal. It's not like we can't reverse it if necessary but there probably isn't a lot of IP tied up into the icons.

**Comment by lanwen** [comment]
I think we should add a note that these icons should have at least credentials

**Comment by herman-rogers** [comment]
These icons should have credentials? Like, add a copyright to them or something?

**Comment by lanwen** [comment]
Exactly

**Comment by herman-rogers** [comment]
Added

**Review by lanwen — APPROVED** [review]

**Pull request merged**
